#!/bin/sh
lftp <<-END
        open ftp.ensembl.org/pub/current_fasta
GET ./acanthochromis_polyacanthus/pep/Acanthochromis_polyacanthus.ASM210954v1.pep.all.fa.gz
GET ./ailuropoda_melanoleuca/pep/Ailuropoda_melanoleuca.ailMel1.pep.all.fa.gz
GET ./amphilophus_citrinellus/pep/Amphilophus_citrinellus.Midas_v5.pep.all.fa.gz
GET ./amphiprion_ocellaris/pep/Amphiprion_ocellaris.AmpOce1.0.pep.all.fa.gz
GET ./amphiprion_percula/pep/Amphiprion_percula.Nemo_v1.pep.all.fa.gz
GET ./anabas_testudineus/pep/Anabas_testudineus.fAnaTes1.1.pep.all.fa.gz
GET ./anas_platyrhynchos/pep/Anas_platyrhynchos.BGI_duck_1.0.pep.all.fa.gz
GET ./anolis_carolinensis/pep/Anolis_carolinensis.AnoCar2.0.pep.all.fa.gz
GET ./aotus_nancymaae/pep/Aotus_nancymaae.Anan_2.0.pep.all.fa.gz
GET ./astatotilapia_calliptera/pep/Astatotilapia_calliptera.fAstCal1.2.pep.all.fa.gz
GET ./astyanax_mexicanus/pep/Astyanax_mexicanus.Astyanax_mexicanus-2.0.pep.all.fa.gz
GET ./bos_taurus/pep/Bos_taurus.ARS-UCD1.2.pep.all.fa.gz
GET ./caenorhabditis_elegans/pep/Caenorhabditis_elegans.WBcel235.pep.all.fa.gz
GET ./callithrix_jacchus/pep/Callithrix_jacchus.ASM275486v1.pep.all.fa.gz
GET ./canis_familiaris/pep/Canis_familiaris.CanFam3.1.pep.all.fa.gz
GET ./canis_lupus_dingo/pep/Canis_lupus_dingo.ASM325472v1.pep.all.fa.gz
GET ./capra_hircus/pep/Capra_hircus.ARS1.pep.all.fa.gz
GET ./carlito_syrichta/pep/Carlito_syrichta.Tarsius_syrichta-2.0.1.pep.all.fa.gz
GET ./cavia_aperea/pep/Cavia_aperea.CavAp1.0.pep.all.fa.gz
GET ./cavia_porcellus/pep/Cavia_porcellus.Cavpor3.0.pep.all.fa.gz
GET ./cebus_capucinus/pep/Cebus_capucinus.Cebus_imitator-1.0.pep.all.fa.gz
GET ./cercocebus_atys/pep/Cercocebus_atys.Caty_1.0.pep.all.fa.gz
GET ./chinchilla_lanigera/pep/Chinchilla_lanigera.ChiLan1.0.pep.all.fa.gz
GET ./chlorocebus_sabaeus/pep/Chlorocebus_sabaeus.ChlSab1.1.pep.all.fa.gz
GET ./choloepus_hoffmanni/pep/Choloepus_hoffmanni.choHof1.pep.all.fa.gz
GET ./chrysemys_picta_bellii/pep/Chrysemys_picta_bellii.Chrysemys_picta_bellii-3.0.3.pep.all.fa.gz
GET ./ciona_intestinalis/pep/Ciona_intestinalis.KH.pep.all.fa.gz
GET ./ciona_savignyi/pep/Ciona_savignyi.CSAV2.0.pep.all.fa.gz
GET ./colobus_angolensis_palliatus/pep/Colobus_angolensis_palliatus.Cang.pa_1.0.pep.all.fa.gz
GET ./cricetulus_griseus_chok1gshd/pep/Cricetulus_griseus_chok1gshd.CHOK1GS_HDv1.pep.all.fa.gz
GET ./cricetulus_griseus_crigri/pep/Cricetulus_griseus_crigri.CriGri_1.0.pep.all.fa.gz
GET ./cynoglossus_semilaevis/pep/Cynoglossus_semilaevis.Cse_v1.0.pep.all.fa.gz
GET ./cyprinodon_variegatus/pep/Cyprinodon_variegatus.C_variegatus-1.0.pep.all.fa.gz
GET ./danio_rerio/pep/Danio_rerio.GRCz11.pep.all.fa.gz
GET ./dasypus_novemcinctus/pep/Dasypus_novemcinctus.Dasnov3.0.pep.all.fa.gz
GET ./dipodomys_ordii/pep/Dipodomys_ordii.Dord_2.0.pep.all.fa.gz
GET ./drosophila_melanogaster/pep/Drosophila_melanogaster.BDGP6.pep.all.fa.gz
GET ./echinops_telfairi/pep/Echinops_telfairi.TENREC.pep.all.fa.gz
GET ./eptatretus_burgeri/pep/Eptatretus_burgeri.Eburgeri_3.2.pep.all.fa.gz
GET ./equus_asinus_asinus/pep/Equus_asinus_asinus.ASM303372v1.pep.all.fa.gz
GET ./equus_caballus/pep/Equus_caballus.EquCab3.0.pep.all.fa.gz
GET ./erinaceus_europaeus/pep/Erinaceus_europaeus.HEDGEHOG.pep.all.fa.gz
GET ./esox_lucius/pep/Esox_lucius.Eluc_V3.pep.all.fa.gz
GET ./felis_catus/pep/Felis_catus.Felis_catus_9.0.pep.all.fa.gz
GET ./ficedula_albicollis/pep/Ficedula_albicollis.FicAlb_1.4.pep.all.fa.gz
GET ./fukomys_damarensis/pep/Fukomys_damarensis.DMR_v1.0.pep.all.fa.gz
GET ./fundulus_heteroclitus/pep/Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa.gz
GET ./gadus_morhua/pep/Gadus_morhua.gadMor1.pep.all.fa.gz
GET ./gallus_gallus/pep/Gallus_gallus.GRCg6a.pep.all.fa.gz
GET ./gambusia_affinis/pep/Gambusia_affinis.ASM309773v1.pep.all.fa.gz
GET ./gasterosteus_aculeatus/pep/Gasterosteus_aculeatus.BROADS1.pep.all.fa.gz
GET ./gopherus_agassizii/pep/Gopherus_agassizii.ASM289641v1.pep.all.fa.gz
GET ./gorilla_gorilla/pep/Gorilla_gorilla.gorGor4.pep.all.fa.gz
GET ./haplochromis_burtoni/pep/Haplochromis_burtoni.AstBur1.0.pep.all.fa.gz
GET ./heterocephalus_glaber_female/pep/Heterocephalus_glaber_female.HetGla_female_1.0.pep.all.fa.gz
GET ./heterocephalus_glaber_male/pep/Heterocephalus_glaber_male.HetGla_1.0.pep.all.fa.gz
GET ./hippocampus_comes/pep/Hippocampus_comes.H_comes_QL1_v1.pep.all.fa.gz
GET ./homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz
GET ./ictalurus_punctatus/pep/Ictalurus_punctatus.IpCoco_1.2.pep.all.fa.gz
GET ./ictidomys_tridecemlineatus/pep/Ictidomys_tridecemlineatus.SpeTri2.0.pep.all.fa.gz
GET ./jaculus_jaculus/pep/Jaculus_jaculus.JacJac1.0.pep.all.fa.gz
GET ./kryptolebias_marmoratus/pep/Kryptolebias_marmoratus.ASM164957v1.pep.all.fa.gz
GET ./labrus_bergylta/pep/Labrus_bergylta.BallGen_V1.pep.all.fa.gz
GET ./latimeria_chalumnae/pep/Latimeria_chalumnae.LatCha1.pep.all.fa.gz
GET ./lepisosteus_oculatus/pep/Lepisosteus_oculatus.LepOcu1.pep.all.fa.gz
GET ./loxodonta_africana/pep/Loxodonta_africana.loxAfr3.pep.all.fa.gz
GET ./macaca_fascicularis/pep/Macaca_fascicularis.Macaca_fascicularis_5.0.pep.all.fa.gz
GET ./macaca_mulatta/pep/Macaca_mulatta.Mmul_8.0.1.pep.all.fa.gz
GET ./macaca_nemestrina/pep/Macaca_nemestrina.Mnem_1.0.pep.all.fa.gz
GET ./mandrillus_leucophaeus/pep/Mandrillus_leucophaeus.Mleu.le_1.0.pep.all.fa.gz
GET ./mastacembelus_armatus/pep/Mastacembelus_armatus.fMasArm1.1.pep.all.fa.gz
GET ./maylandia_zebra/pep/Maylandia_zebra.M_zebra_UMD2a.pep.all.fa.gz
GET ./meleagris_gallopavo/pep/Meleagris_gallopavo.UMD2.pep.all.fa.gz
GET ./mesocricetus_auratus/pep/Mesocricetus_auratus.MesAur1.0.pep.all.fa.gz
GET ./microcebus_murinus/pep/Microcebus_murinus.Mmur_3.0.pep.all.fa.gz
GET ./microtus_ochrogaster/pep/Microtus_ochrogaster.MicOch1.0.pep.all.fa.gz
GET ./mola_mola/pep/Mola_mola.ASM169857v1.pep.all.fa.gz
GET ./monodelphis_domestica/pep/Monodelphis_domestica.monDom5.pep.all.fa.gz
GET ./monopterus_albus/pep/Monopterus_albus.M_albus_1.0.pep.all.fa.gz
GET ./mus_caroli/pep/Mus_caroli.CAROLI_EIJ_v1.1.pep.all.fa.gz
GET ./mus_musculus/pep/Mus_musculus.GRCm38.pep.all.fa.gz
GET ./mus_musculus_129s1svimj/pep/Mus_musculus_129s1svimj.129S1_SvImJ_v1.pep.all.fa.gz
GET ./mus_musculus_aj/pep/Mus_musculus_aj.A_J_v1.pep.all.fa.gz
GET ./mus_musculus_akrj/pep/Mus_musculus_akrj.AKR_J_v1.pep.all.fa.gz
GET ./mus_musculus_balbcj/pep/Mus_musculus_balbcj.BALB_cJ_v1.pep.all.fa.gz
GET ./mus_musculus_c3hhej/pep/Mus_musculus_c3hhej.C3H_HeJ_v1.pep.all.fa.gz
GET ./mus_musculus_c57bl6nj/pep/Mus_musculus_c57bl6nj.C57BL_6NJ_v1.pep.all.fa.gz
GET ./mus_musculus_casteij/pep/Mus_musculus_casteij.CAST_EiJ_v1.pep.all.fa.gz
GET ./mus_musculus_cbaj/pep/Mus_musculus_cbaj.CBA_J_v1.pep.all.fa.gz
GET ./mus_musculus_dba2j/pep/Mus_musculus_dba2j.DBA_2J_v1.pep.all.fa.gz
GET ./mus_musculus_fvbnj/pep/Mus_musculus_fvbnj.FVB_NJ_v1.pep.all.fa.gz
GET ./mus_musculus_lpj/pep/Mus_musculus_lpj.LP_J_v1.pep.all.fa.gz
GET ./mus_musculus_nodshiltj/pep/Mus_musculus_nodshiltj.NOD_ShiLtJ_v1.pep.all.fa.gz
GET ./mus_musculus_nzohlltj/pep/Mus_musculus_nzohlltj.NZO_HlLtJ_v1.pep.all.fa.gz
GET ./mus_musculus_pwkphj/pep/Mus_musculus_pwkphj.PWK_PhJ_v1.pep.all.fa.gz
GET ./mus_musculus_wsbeij/pep/Mus_musculus_wsbeij.WSB_EiJ_v1.pep.all.fa.gz
GET ./mus_pahari/pep/Mus_pahari.PAHARI_EIJ_v1.1.pep.all.fa.gz
GET ./mus_spretus/pep/Mus_spretus.SPRET_EiJ_v1.pep.all.fa.gz
GET ./mustela_putorius_furo/pep/Mustela_putorius_furo.MusPutFur1.0.pep.all.fa.gz
GET ./myotis_lucifugus/pep/Myotis_lucifugus.Myoluc2.0.pep.all.fa.gz
GET ./nannospalax_galili/pep/Nannospalax_galili.S.galili_v1.0.pep.all.fa.gz
GET ./neolamprologus_brichardi/pep/Neolamprologus_brichardi.NeoBri1.0.pep.all.fa.gz
GET ./nomascus_leucogenys/pep/Nomascus_leucogenys.Nleu_3.0.pep.all.fa.gz
GET ./notamacropus_eugenii/pep/Notamacropus_eugenii.Meug_1.0.pep.all.fa.gz
GET ./ochotona_princeps/pep/Ochotona_princeps.OchPri2.0-Ens.pep.all.fa.gz
GET ./octodon_degus/pep/Octodon_degus.OctDeg1.0.pep.all.fa.gz
GET ./oreochromis_niloticus/pep/Oreochromis_niloticus.Orenil1.0.pep.all.fa.gz
GET ./ornithorhynchus_anatinus/pep/Ornithorhynchus_anatinus.OANA5.pep.all.fa.gz
GET ./oryctolagus_cuniculus/pep/Oryctolagus_cuniculus.OryCun2.0.pep.all.fa.gz
GET ./oryzias_latipes/pep/Oryzias_latipes.ASM223467v1.pep.all.fa.gz
GET ./oryzias_latipes_hni/pep/Oryzias_latipes_hni.ASM223471v1.pep.all.fa.gz
GET ./oryzias_latipes_hsok/pep/Oryzias_latipes_hsok.ASM223469v1.pep.all.fa.gz
GET ./oryzias_melastigma/pep/Oryzias_melastigma.Om_v0.7.RACA.pep.all.fa.gz
GET ./otolemur_garnettii/pep/Otolemur_garnettii.OtoGar3.pep.all.fa.gz
GET ./ovis_aries/pep/Ovis_aries.Oar_v3.1.pep.all.fa.gz
GET ./pan_paniscus/pep/Pan_paniscus.panpan1.1.pep.all.fa.gz
GET ./pan_troglodytes/pep/Pan_troglodytes.Pan_tro_3.0.pep.all.fa.gz
GET ./panthera_pardus/pep/Panthera_pardus.PanPar1.0.pep.all.fa.gz
GET ./panthera_tigris_altaica/pep/Panthera_tigris_altaica.PanTig1.0.pep.all.fa.gz
GET ./papio_anubis/pep/Papio_anubis.Panu_3.0.pep.all.fa.gz
GET ./paramormyrops_kingsleyae/pep/Paramormyrops_kingsleyae.PKINGS_0.1.pep.all.fa.gz
GET ./pelodiscus_sinensis/pep/Pelodiscus_sinensis.PelSin_1.0.pep.all.fa.gz
GET ./periophthalmus_magnuspinnatus/pep/Periophthalmus_magnuspinnatus.PM.fa.pep.all.fa.gz
GET ./peromyscus_maniculatus_bairdii/pep/Peromyscus_maniculatus_bairdii.Pman_1.0.pep.all.fa.gz
GET ./petromyzon_marinus/pep/Petromyzon_marinus.Pmarinus_7.0.pep.all.fa.gz
GET ./phascolarctos_cinereus/pep/Phascolarctos_cinereus.phaCin_tgac_v2.0.pep.all.fa.gz
GET ./poecilia_formosa/pep/Poecilia_formosa.PoeFor_5.1.2.pep.all.fa.gz
GET ./poecilia_latipinna/pep/Poecilia_latipinna.P_latipinna-1.0.pep.all.fa.gz
GET ./poecilia_mexicana/pep/Poecilia_mexicana.P_mexicana-1.0.pep.all.fa.gz
GET ./poecilia_reticulata/pep/Poecilia_reticulata.Guppy_female_1.0_MT.pep.all.fa.gz
GET ./pongo_abelii/pep/Pongo_abelii.PPYG2.pep.all.fa.gz
GET ./procavia_capensis/pep/Procavia_capensis.proCap1.pep.all.fa.gz
GET ./propithecus_coquereli/pep/Propithecus_coquereli.Pcoq_1.0.pep.all.fa.gz
GET ./pteropus_vampyrus/pep/Pteropus_vampyrus.pteVam1.pep.all.fa.gz
GET ./pundamilia_nyererei/pep/Pundamilia_nyererei.PunNye1.0.pep.all.fa.gz
GET ./pygocentrus_nattereri/pep/Pygocentrus_nattereri.Pygocentrus_nattereri-1.0.2.pep.all.fa.gz
GET ./rattus_norvegicus/pep/Rattus_norvegicus.Rnor_6.0.pep.all.fa.gz
GET ./rhinopithecus_bieti/pep/Rhinopithecus_bieti.ASM169854v1.pep.all.fa.gz
GET ./rhinopithecus_roxellana/pep/Rhinopithecus_roxellana.Rrox_v1.pep.all.fa.gz
GET ./saccharomyces_cerevisiae/pep/Saccharomyces_cerevisiae.R64-1-1.pep.all.fa.gz
GET ./saimiri_boliviensis_boliviensis/pep/Saimiri_boliviensis_boliviensis.SaiBol1.0.pep.all.fa.gz
GET ./sarcophilus_harrisii/pep/Sarcophilus_harrisii.DEVIL7.0.pep.all.fa.gz
GET ./scleropages_formosus/pep/Scleropages_formosus.ASM162426v1.pep.all.fa.gz
GET ./scophthalmus_maximus/pep/Scophthalmus_maximus.ASM318616v1.pep.all.fa.gz
GET ./seriola_dumerili/pep/Seriola_dumerili.Sdu_1.0.pep.all.fa.gz
GET ./seriola_lalandi_dorsalis/pep/Seriola_lalandi_dorsalis.Sedor1.pep.all.fa.gz
GET ./sorex_araneus/pep/Sorex_araneus.COMMON_SHREW1.pep.all.fa.gz
GET ./sphenodon_punctatus/pep/Sphenodon_punctatus.ASM311381v1.pep.all.fa.gz
GET ./stegastes_partitus/pep/Stegastes_partitus.Stegastes_partitus-1.0.2.pep.all.fa.gz
GET ./sus_scrofa/pep/Sus_scrofa.Sscrofa11.1.pep.all.fa.gz
GET ./taeniopygia_guttata/pep/Taeniopygia_guttata.taeGut3.2.4.pep.all.fa.gz
GET ./takifugu_rubripes/pep/Takifugu_rubripes.FUGU5.pep.all.fa.gz
GET ./tetraodon_nigroviridis/pep/Tetraodon_nigroviridis.TETRAODON8.pep.all.fa.gz
GET ./tupaia_belangeri/pep/Tupaia_belangeri.TREESHREW.pep.all.fa.gz
GET ./tursiops_truncatus/pep/Tursiops_truncatus.turTru1.pep.all.fa.gz
GET ./ursus_americanus/pep/Ursus_americanus.ASM334442v1.pep.all.fa.gz
GET ./ursus_maritimus/pep/Ursus_maritimus.UrsMar_1.0.pep.all.fa.gz
GET ./vicugna_pacos/pep/Vicugna_pacos.vicPac1.pep.all.fa.gz
GET ./vulpes_vulpes/pep/Vulpes_vulpes.VulVul2.2.pep.all.fa.gz
GET ./xenopus_tropicalis/pep/Xenopus_tropicalis.JGI_4.2.pep.all.fa.gz
GET ./xiphophorus_couchianus/pep/Xiphophorus_couchianus.Xiphophorus_couchianus-4.0.1.pep.all.fa.gz
GET ./xiphophorus_maculatus/pep/Xiphophorus_maculatus.X_maculatus-5.0-male.pep.all.fa.gz
END

